name: Makefile CI

env: 
  ENV: 'DEV'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Test and publish coverage
      run: |
        make
        cp SimpleSearch.Tests/TestResults/*/coverage.info SimpleSearch.Tests/TestResults/coverage.info 

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        path-to-lcov: "SimpleSearch.Tests/TestResults/coverage.info"
        github-token: ${{ secrets.github_token }}

