name: Makefile CI

env:
  ENV: 'DEV'
  DJANGO_SETTINGS_MODULE: 'settings.local'
on:
  push:
    branches: [ python ]
  pull_request:
    branches: [ python ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v1
    - uses: knowsuchagency/poetry-install@v1
    - name: Test and publish coverage
      run: |
        make
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        path-to-lcov: "coverage.lcov"
        github-token: ${{ secrets.github_token }}

