name: Makefile CI

env: 
  ENV: 'DEV'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Poetry Install
      # You may pin to the exact commit or the version.
      # uses: knowsuchagency/poetry-install@7ed80d49910319d3e14ac262a5c81f681de48de0
      uses: knowsuchagency/poetry-install@v2
      
    - name: Test and publish coverage
      run: |
        make
        cp SimpleSearch.Tests/TestResults/*/coverage.info SimpleSearch.Tests/TestResults/coverage.info 

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        path-to-lcov: "SimpleSearch.Tests/TestResults/coverage.info"
        github-token: ${{ secrets.github_token }}

